CREATE TABLE TEAMS (
    ID INT PRIMARY KEY,
    NAME VARCHAR
);

CREATE TABLE GAMES (
    ID INT PRIMARY KEY,
    HOME_TEAM INT,
    HOME_TEAM_SCORE INT,
    AWAY_TEAM INT,
    AWAY_TEAM_SCORE INT
);
